apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        fsGroup: 1000
      restartPolicy: Always

      initContainers:
        - name: volume-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /var/jenkins_home && chmod -R 777 /var/jenkins_home"]
          volumeMounts:
            - mountPath: "/var/jenkins_home"
              name: jenkins-home

      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          securityContext:
            runAsUser: 1000
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/var/jenkins_home"
              name: jenkins-home
          resources:
            requests:
              memory: "512Mi" 
              cpu: "250m"    
            limits:
              memory: "1Gi"
              cpu: "500m"

      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-pvc
