apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: dev
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: jenkins-disk 
    fsType: ext4